package com.epam.architecture.soapws.impl;

import jakarta.jws.HandlerChain;
import jakarta.xml.ws.*;

import javax.xml.namespace.QName;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@HandlerChain(file = "clientHandler.xml")
@WebServiceClient(name = "AdminSOAPServiceImplService", targetNamespace = "http://impl.SOAPws.architecture.epam.com/", wsdlLocation = "http://localhost:8082/JavaDesignAndArchitecture_war_exploded/admin?wsdl")
public class AdminSOAPServiceImplService
        extends Service {

    private final static URL ADMINSOAPSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException ADMINSOAPSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName ADMINSOAPSERVICEIMPLSERVICE_QNAME = new QName("http://impl.SOAPws.architecture.epam.com/", "AdminSOAPServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8082/JavaDesignAndArchitecture_war_exploded/admin?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ADMINSOAPSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        ADMINSOAPSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public AdminSOAPServiceImplService() {
        super(__getWsdlLocation(), ADMINSOAPSERVICEIMPLSERVICE_QNAME);
    }

    public AdminSOAPServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ADMINSOAPSERVICEIMPLSERVICE_QNAME, features);
    }

    public AdminSOAPServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, ADMINSOAPSERVICEIMPLSERVICE_QNAME);
    }

    public AdminSOAPServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ADMINSOAPSERVICEIMPLSERVICE_QNAME, features);
    }

    public AdminSOAPServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AdminSOAPServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    private static URL __getWsdlLocation() {
        if (ADMINSOAPSERVICEIMPLSERVICE_EXCEPTION != null) {
            throw ADMINSOAPSERVICEIMPLSERVICE_EXCEPTION;
        }
        return ADMINSOAPSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

    /**
     * @return returns AdminSOAPService
     */
    @WebEndpoint(name = "AdminSOAPServiceImplPort")
    public AdminSOAPService getAdminSOAPServiceImplPort() {
        return super.getPort(new QName("http://impl.SOAPws.architecture.epam.com/", "AdminSOAPServiceImplPort"), AdminSOAPService.class);
    }

    /**
     * @param features A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns AdminSOAPService
     */
    @WebEndpoint(name = "AdminSOAPServiceImplPort")
    public AdminSOAPService getAdminSOAPServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.SOAPws.architecture.epam.com/", "AdminSOAPServiceImplPort"), AdminSOAPService.class, features);
    }

}
