package com.epam.architecture.soapws.impl;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "AdminSOAPService", targetNamespace = "http://SOAPws.architecture.epam.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface AdminSOAPService {


    /**
     * @param arg1
     * @param arg0
     * @return returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://SOAPws.architecture.epam.com/AdminSOAPService/addNewUserRequest", output = "http://SOAPws.architecture.epam.com/AdminSOAPService/addNewUserResponse")
    public boolean addNewUser(
            @WebParam(name = "arg0", partName = "arg0")
                    String arg0,
            @WebParam(name = "arg1", partName = "arg1")
                    String arg1);

    /**
     * @param arg0
     * @return returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://SOAPws.architecture.epam.com/AdminSOAPService/banUserRequest", output = "http://SOAPws.architecture.epam.com/AdminSOAPService/banUserResponse")
    public boolean banUser(
            @WebParam(name = "arg0", partName = "arg0")
                    String arg0);

    /**
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://SOAPws.architecture.epam.com/AdminSOAPService/takeHistoryRequest", output = "http://SOAPws.architecture.epam.com/AdminSOAPService/takeHistoryResponse")
    public String takeHistory();

    /**
     *
     */
    @WebMethod
    @Action(input = "http://SOAPws.architecture.epam.com/AdminSOAPService/saveRequest", output = "http://SOAPws.architecture.epam.com/AdminSOAPService/saveResponse")
    public void save();

}
