package com.epam.architecture.soapws.impl;

import jakarta.jws.HandlerChain;
import jakarta.xml.ws.*;

import javax.xml.namespace.QName;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@HandlerChain(file = "clientHandler.xml")
@WebServiceClient(name = "BookSOAPServiceImplService", targetNamespace = "http://impl.SOAPws.architecture.epam.com/", wsdlLocation = "http://localhost:8082/JavaDesignAndArchitecture_war_exploded/book?wsdl")
public class BookSOAPServiceImplService
        extends Service {

    private final static URL BOOKSOAPSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException BOOKSOAPSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName BOOKSOAPSERVICEIMPLSERVICE_QNAME = new QName("http://impl.SOAPws.architecture.epam.com/", "BookSOAPServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8082/JavaDesignAndArchitecture_war_exploded/book?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BOOKSOAPSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        BOOKSOAPSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public BookSOAPServiceImplService() {
        super(__getWsdlLocation(), BOOKSOAPSERVICEIMPLSERVICE_QNAME);
    }

    public BookSOAPServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BOOKSOAPSERVICEIMPLSERVICE_QNAME, features);
    }

    public BookSOAPServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, BOOKSOAPSERVICEIMPLSERVICE_QNAME);
    }

    public BookSOAPServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BOOKSOAPSERVICEIMPLSERVICE_QNAME, features);
    }

    public BookSOAPServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BookSOAPServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    private static URL __getWsdlLocation() {
        if (BOOKSOAPSERVICEIMPLSERVICE_EXCEPTION != null) {
            throw BOOKSOAPSERVICEIMPLSERVICE_EXCEPTION;
        }
        return BOOKSOAPSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

    /**
     * @return returns BookSOAPService
     */
    @WebEndpoint(name = "BookSOAPServiceImplPort")
    public BookSOAPService getBookSOAPServiceImplPort() {
        return super.getPort(new QName("http://impl.SOAPws.architecture.epam.com/", "BookSOAPServiceImplPort"), BookSOAPService.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns BookSOAPService
     */
    @WebEndpoint(name = "BookSOAPServiceImplPort")
    public BookSOAPService getBookSOAPServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.SOAPws.architecture.epam.com/", "BookSOAPServiceImplPort"), BookSOAPService.class, features);
    }

}
