package com.epam.architecture.soapws.impl;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "BookSOAPService", targetNamespace = "http://SOAPws.architecture.epam.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface BookSOAPService {


    /**
     * @param arg3
     * @param arg2
     * @param arg4
     * @param arg1
     * @param arg0
     * @return returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://SOAPws.architecture.epam.com/BookSOAPService/addBookRequest", output = "http://SOAPws.architecture.epam.com/BookSOAPService/addBookResponse")
    public boolean addBook(
            @WebParam(name = "arg0", partName = "arg0")
                    String arg0,
            @WebParam(name = "arg1", partName = "arg1")
                    String arg1,
            @WebParam(name = "arg2", partName = "arg2")
                    int arg2,
            @WebParam(name = "arg3", partName = "arg3")
                    int arg3,
            @WebParam(name = "arg4", partName = "arg4")
                    String arg4);

    /**
     * @param arg0
     * @return returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://SOAPws.architecture.epam.com/BookSOAPService/deleteBookRequest", output = "http://SOAPws.architecture.epam.com/BookSOAPService/deleteBookResponse")
    public boolean deleteBook(
            @WebParam(name = "arg0", partName = "arg0")
                    String arg0);

    /**
     * @param arg0
     * @return returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://SOAPws.architecture.epam.com/BookSOAPService/addAuthorRequest", output = "http://SOAPws.architecture.epam.com/BookSOAPService/addAuthorResponse")
    public boolean addAuthor(
            @WebParam(name = "arg0", partName = "arg0")
                    String arg0);

    /**
     * @param arg0
     * @return returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://SOAPws.architecture.epam.com/BookSOAPService/deleteAuthorRequest", output = "http://SOAPws.architecture.epam.com/BookSOAPService/deleteAuthorResponse")
    public boolean deleteAuthor(
            @WebParam(name = "arg0", partName = "arg0")
                    String arg0);

    /**
     *
     */
    @WebMethod
    @Action(input = "http://SOAPws.architecture.epam.com/BookSOAPService/saveRequest", output = "http://SOAPws.architecture.epam.com/BookSOAPService/saveResponse")
    public void save();

}
