package com.epam.architecture.soapws.impl;

import com.epam.architecture.soapws.Book;
import com.epam.architecture.soapws.BookArray;
import com.epam.architecture.soapws.ObjectFactory;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "SearchSOAPService", targetNamespace = "http://SOAPws.architecture.epam.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
        ObjectFactory.class
})
public interface SearchSOAPService {


    /**
     * @param arg0
     * @return returns com.epam.architecture.soapws.BookArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://SOAPws.architecture.epam.com/SearchSOAPService/booksByPartAuthorNameRequest", output = "http://SOAPws.architecture.epam.com/SearchSOAPService/booksByPartAuthorNameResponse")
    BookArray booksByPartAuthorName(
            @WebParam(name = "arg0", partName = "arg0")
                    String arg0);

    /**
     * @param arg2
     * @param arg1
     * @param arg0
     * @return returns com.epam.architecture.soapws.BookArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://SOAPws.architecture.epam.com/SearchSOAPService/booksByYearPagesPartNameRequest", output = "http://SOAPws.architecture.epam.com/SearchSOAPService/booksByYearPagesPartNameResponse")
    BookArray booksByYearPagesPartName(
            @WebParam(name = "arg0", partName = "arg0")
                    int arg0,
            @WebParam(name = "arg1", partName = "arg1")
                    int arg1,
            @WebParam(name = "arg2", partName = "arg2")
                    String arg2);

    /**
     * @param arg0
     * @return returns com.epam.architecture.soapws.BookArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://SOAPws.architecture.epam.com/SearchSOAPService/booksByPartNameRequest", output = "http://SOAPws.architecture.epam.com/SearchSOAPService/booksByPartNameResponse")
    BookArray booksByPartName(
            @WebParam(name = "arg0", partName = "arg0")
                    String arg0);

    /**
     * @param arg0
     * @return returns com.epam.architecture.soapws.Book
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://SOAPws.architecture.epam.com/SearchSOAPService/bookByISBNRequest", output = "http://SOAPws.architecture.epam.com/SearchSOAPService/bookByISBNResponse")
    Book bookByISBN(
            @WebParam(name = "arg0", partName = "arg0")
                    String arg0);

    /**
     * @param arg1
     * @param arg0
     * @return returns com.epam.architecture.soapws.BookArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://SOAPws.architecture.epam.com/SearchSOAPService/booksByYearRangeRequest", output = "http://SOAPws.architecture.epam.com/SearchSOAPService/booksByYearRangeResponse")
    BookArray booksByYearRange(
            @WebParam(name = "arg0", partName = "arg0")
                    int arg0,
            @WebParam(name = "arg1", partName = "arg1")
                    int arg1);

}
