package com.epam.architecture.soapws.impl;

import jakarta.jws.HandlerChain;
import jakarta.xml.ws.*;

import javax.xml.namespace.QName;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@HandlerChain(file = "clientHandler.xml")
@WebServiceClient(name = "SearchSOAPServiceImplService", targetNamespace = "http://impl.SOAPws.architecture.epam.com/", wsdlLocation = "http://localhost:8082/JavaDesignAndArchitecture_war_exploded/search?wsdl")
public class SearchSOAPServiceImplService
        extends Service {

    private final static URL SEARCHSOAPSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SEARCHSOAPSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName SEARCHSOAPSERVICEIMPLSERVICE_QNAME = new QName("http://impl.SOAPws.architecture.epam.com/", "SearchSOAPServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8082/JavaDesignAndArchitecture_war_exploded/search?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SEARCHSOAPSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        SEARCHSOAPSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public SearchSOAPServiceImplService() {
        super(__getWsdlLocation(), SEARCHSOAPSERVICEIMPLSERVICE_QNAME);
    }

    public SearchSOAPServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SEARCHSOAPSERVICEIMPLSERVICE_QNAME, features);
    }

    public SearchSOAPServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SEARCHSOAPSERVICEIMPLSERVICE_QNAME);
    }

    public SearchSOAPServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SEARCHSOAPSERVICEIMPLSERVICE_QNAME, features);
    }

    public SearchSOAPServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SearchSOAPServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    private static URL __getWsdlLocation() {
        if (SEARCHSOAPSERVICEIMPLSERVICE_EXCEPTION != null) {
            throw SEARCHSOAPSERVICEIMPLSERVICE_EXCEPTION;
        }
        return SEARCHSOAPSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

    /**
     * @return returns SearchSOAPService
     */
    @WebEndpoint(name = "SearchSOAPServiceImplPort")
    public SearchSOAPService getSearchSOAPServiceImplPort() {
        return super.getPort(new QName("http://impl.SOAPws.architecture.epam.com/", "SearchSOAPServiceImplPort"), SearchSOAPService.class);
    }

    /**
     * @param features A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns SearchSOAPService
     */
    @WebEndpoint(name = "SearchSOAPServiceImplPort")
    public SearchSOAPService getSearchSOAPServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.SOAPws.architecture.epam.com/", "SearchSOAPServiceImplPort"), SearchSOAPService.class, features);
    }

}
