package com.epam.architecture.soapws.impl;


import jakarta.xml.ws.WebFault;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebFault(name = "SOAPException", targetNamespace = "http://SOAPws.architecture.epam.com/")
public class SOAPException
        extends Exception {

    /**
     * Java type that goes as soapenv:Fault detail element.
     */
    private com.epam.architecture.soapws.SOAPException faultInfo;

    /**
     * @param faultInfo
     * @param message
     */
    public SOAPException(String message, com.epam.architecture.soapws.SOAPException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * @param faultInfo
     * @param cause
     * @param message
     */
    public SOAPException(String message, com.epam.architecture.soapws.SOAPException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * @return returns fault bean: com.epam.architecture.soapws.SOAPException
     */
    public com.epam.architecture.soapws.SOAPException getFaultInfo() {
        return faultInfo;
    }

}
