package com.epam.architecture.soapws.impl;

import jakarta.jws.HandlerChain;
import jakarta.xml.ws.*;

import javax.xml.namespace.QName;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@HandlerChain(file = "clientHandler.xml")
@WebServiceClient(name = "UserSOAPServiceImplService", targetNamespace = "http://impl.SOAPws.architecture.epam.com/", wsdlLocation = "http://localhost:8082/JavaDesignAndArchitecture_war_exploded/user?wsdl")
public class UserSOAPServiceImplService
        extends Service {

    private final static URL USERSOAPSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException USERSOAPSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName USERSOAPSERVICEIMPLSERVICE_QNAME = new QName("http://impl.SOAPws.architecture.epam.com/", "UserSOAPServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8082/JavaDesignAndArchitecture_war_exploded/user?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        USERSOAPSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        USERSOAPSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public UserSOAPServiceImplService() {
        super(__getWsdlLocation(), USERSOAPSERVICEIMPLSERVICE_QNAME);
    }

    public UserSOAPServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), USERSOAPSERVICEIMPLSERVICE_QNAME, features);
    }

    public UserSOAPServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, USERSOAPSERVICEIMPLSERVICE_QNAME);
    }

    public UserSOAPServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, USERSOAPSERVICEIMPLSERVICE_QNAME, features);
    }

    public UserSOAPServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserSOAPServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    private static URL __getWsdlLocation() {
        if (USERSOAPSERVICEIMPLSERVICE_EXCEPTION != null) {
            throw USERSOAPSERVICEIMPLSERVICE_EXCEPTION;
        }
        return USERSOAPSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

    /**
     * @return returns UserSOAPService
     */
    @WebEndpoint(name = "UserSOAPServiceImplPort")
    public UserSOAPService getUserSOAPServiceImplPort() {
        return super.getPort(new QName("http://impl.SOAPws.architecture.epam.com/", "UserSOAPServiceImplPort"), UserSOAPService.class);
    }

    /**
     * @param features A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns UserSOAPService
     */
    @WebEndpoint(name = "UserSOAPServiceImplPort")
    public UserSOAPService getUserSOAPServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.SOAPws.architecture.epam.com/", "UserSOAPServiceImplPort"), UserSOAPService.class, features);
    }

}
