package com.epam.architecture.soapws.impl;

import com.epam.architecture.soapws.BookArray;
import com.epam.architecture.soapws.ObjectFactory;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "UserSOAPService", targetNamespace = "http://SOAPws.architecture.epam.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
        ObjectFactory.class
})
public interface UserSOAPService {


    /**
     * @param arg2
     * @param arg1
     * @param arg0
     * @return returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://SOAPws.architecture.epam.com/UserSOAPService/addBookmarkRequest", output = "http://SOAPws.architecture.epam.com/UserSOAPService/addBookmarkResponse")
    boolean addBookmark(
            @WebParam(name = "arg0", partName = "arg0")
                    String arg0,
            @WebParam(name = "arg1", partName = "arg1")
                    String arg1,
            @WebParam(name = "arg2", partName = "arg2")
                    int arg2);

    /**
     * @param arg2
     * @param arg1
     * @param arg0
     * @return returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://SOAPws.architecture.epam.com/UserSOAPService/deleteBookmarkRequest", output = "http://SOAPws.architecture.epam.com/UserSOAPService/deleteBookmarkResponse")
    boolean deleteBookmark(
            @WebParam(name = "arg0", partName = "arg0")
                    String arg0,
            @WebParam(name = "arg1", partName = "arg1")
                    String arg1,
            @WebParam(name = "arg2", partName = "arg2")
                    int arg2);

    /**
     * @param arg0
     * @return returns com.epam.architecture.soapws.BookArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://SOAPws.architecture.epam.com/UserSOAPService/booksWithUserBookmarksRequest", output = "http://SOAPws.architecture.epam.com/UserSOAPService/booksWithUserBookmarksResponse")
    BookArray booksWithUserBookmarks(
            @WebParam(name = "arg0", partName = "arg0")
                    String arg0);

    /**
     *
     */
    @WebMethod
    @Action(input = "http://SOAPws.architecture.epam.com/UserSOAPService/saveRequest", output = "http://SOAPws.architecture.epam.com/UserSOAPService/saveResponse")
    void save();

}
